### ISSUE TITLE
Windows Defender

### ISSUE THREAD

**Issue by HanaO00** [CHEF-KOCH/GamingTweaks#3]
Hello,

Do you think that Windows Defender is really enough as an AV ? Or i need something like ESET, Avast..

**Comment by CHEF-KOCH** [comment]
![fefe](https://user-images.githubusercontent.com/727123/44046938-47537520-9f2d-11e8-8819-68d8130db02c.png)

https://www.av-test.org/de/antivirus/privat-windows/windows-10/juni-2018/

I think there all pretty much the same. If WD continues to improve the sandboxing performance (which caused massive performance issue in the past) they could be the same like Eset & Co. Eset and parts of Kaspersky a special cause they are written in ASM that's why they are here and there a little bit faster.
