### ISSUE TITLE
 Antivirus + GameDVR question

### ISSUE THREAD

**Issue by ArmynC** [CHEF-KOCH/GamingTweaks#4]
1. I saw that there was already an issue on this topic but I will resume it. Is a wise choice to recommend only Windows Defender? It's a brand new product I know but the speed isn't really a factor here & the 0 day + ransomware isn't that good... As you can see [here](https://www.av-test.org/en/antivirus/home-windows/) it takes up to 50% of the performance (average 20%) and there are more processes like Windows Smart Filter and so on (that are integrated) compared to other AV solutions... Isn't better to recommend no AV use than it, or a better free AV like BitDefender or Kaspersky?

2. I wanted to delete a page from my wiki git (a game configuration) but it isn't a good 'subject' for my git (windows performance...), there being better sources like this one.
See: DVR and Gamemode are recommended to be disabled and I didn't saw on your page (even the games recommends it).. I'll leave it here..

```
## Disable Xbox Game DVR

Users experiencing low FPS or FPS loss after upgrading to Windows 10 may resolve the issue by disabling the Xbox DVR feature.

1. Open Registry Editor (Run > regedit).
2. Navigate to `HKEY_CURRENT_USERSystemGameConfigStore`
3. Set the value of DWORD `GameDVR_Enabled` to `0`.
4. Go to `HKEY_LOCAL_MACHINESOFTWAREPoliciesMicrosoftWindows`
5. Create key `GameDVR`.
6. Create DWORD 32bit called `AllowGameDVR` and set to `0`.
7. Restart your computer.

## Disable Xbox Game Mode

The Game Mode feature can optimize your Windows 10 PC for an improvement in-game performance and the best possible experience. When Game Mode is turned on, Windows prioritizes your PC's resources so you get the best possible game performance. However, doesn't always improve gaming and app performance, even worse, it can lower the performance.

1. Open Registry Editor (Run > regedit).
2. Go to `HKEY_CURRENT_USERSoftwareMicrosoftGameBar`
3. Create DWORDs 32bit called `AllowAutoGameMode` & `AutoGameModeEnabled` and set them to `0`.
4. Restart your computer.

## Disable Fullscreen Optimizations

Fullscreen optimizations may lead to better gaming and app performance when they are running in Fullscreen mode. However, Fullscreen optimizations don't always improve gaming and app performance, even worse, it can lower the performance.

1. Right click on `csgo.exe` file or shortcut and click on Properties.
2. Click on the Compatibility tab, uncheck `Disable Fullscreen optimizations` and click on OK.

## Use High-Performance power plan

Open Power Options and select the High-Performance power plan or the Ultimate Performance plan for Workstations with Windows 10 Pro. For AMD Ryzen users, there may be a Ryzen specific plan.

## Disable Unnecessary Services

Get [W10Privacy tool](https://winprivacy.de/deutsch-start/download/) to reduce disk load and other workloads (like Telemetry). In the same time, this will enhance your privacy.

## CPU Process Manager

Get [Bitsum Process Lasso](https://bitsum.com/files/processlassosetup64.exe) (pay-to-use or [patch](http://cracksurl.com/process-lasso-pro/) it), to have an advanced process priority optimization and system automation utility with process priority optimization, CPU core affinity optimization, power plan automation, automated rules. 

Modern CPUs are not actually getting very much faster, they are growing parallel (adding cores). This is because we hit the limits of physics. Now, since a thread can only execute on one core (it can be swapped around, but it can only execute on a single core) at a time and can’t be broken up, and most software still has a single-threaded or multi-threaded CPU bound occurrences, it is more important than ever to have a process manager algorithm, and its automation on top of that for custom CPU affinities. So, with more cores, increases the need for a process manager.
```

**Comment by CHEF-KOCH** [comment]
According [from an earlier test WD](https://www.av-test.org/de/news/18-schutzloesungen-fuer-unternehmen-im-test-unter-windows-10/) is as good as other solutions, sure it doesn't have as many gimmicks as other programs but that mostly only confuses users. Even the latest test seems [good enough](https://www.av-test.org/en/antivirus/home-windows/windows-10/october-2018/microsoft-windows-defender-4.18-184014/). I'm not sure why performance is an argument, once the scanner really scans every AV uses as much as possible resources because it's is the purpose to do the job as fast as possible. At the end, it's a matter of taste if you want an AV or not. WD is simply a part of the OS and you can enable/disable it if you like/dislike it. However, if the AV idles it doesn't really take much resources (same like other AV's). 


Disable GameDVR etc is already mentioned.

**Comment by ArmynC** [comment]
Whoops.. I saw it now :) Is that code (but not in the title specified). Anyway that Process Manager isn't good for a specify in the article?

**Comment by CHEF-KOCH** [comment]
`## Use High-Performance power plan

Open Power Options and select the High-Performance power plan or the Ultimate Performance plan for Workstations with Windows 10 Pro. For AMD Ryzen users, there may be a Ryzen specific plan.

## Disable Unnecessary Services

Get [W10Privacy tool](https://winprivacy.de/deutsch-start/download/) to reduce disk load and other workloads (like Telemetry). In the same time, this will enhance your privacy.

## CPU Process Manager

Get [Bitsum Process Lasso](https://bitsum.com/files/processlassosetup64.exe) (pay-to-use or [patch](http://cracksurl.com/process-lasso-pro/) it), to have an advanced process priority optimization and system automation utility with process priority optimization, CPU core affinity optimization, power plan automation, automated rules. 

Modern CPUs are not actually getting very much faster, they are growing parallel (adding cores). This is because we hit the limits of physics. Now, since a thread can only execute on one core (it can be swapped around, but it can only execute on a single core) at a time and can’t be broken up, and most software still has a single-threaded or multi-threaded CPU bound occurrences, it is more important than ever to have a process manager algorithm, and its automation on top of that for custom CPU affinities. So, with more cores, increases the need for a process manager.`

1. Ultimate Power Plan doesn't give you an FPS boost. (not needed high performance is good enough) If someone likes to prove me wrong with a video, go ahead but I often stream and I tested all of these tweaks and never got anything from it because the driver regulates this already (in combination with the game).

2. Disable Unnecessary Services - It's true that this helps to reduce some load on CPU and RAM but most services are small in footprint. CPU cycles is what is more interesting and Windows normally takes care of it very well already since Windows 10 (it's not perfect) but this is more for advanced users. If you have 16 GB ram and a decent CPU from 2018, I very much doubt that you get much from it anymore the CPU's are so fast and it's easier to let it enabled. But if you have some time and the will you can go with it and tweak it. In my process explorer, the first shown Microsoft "app" (it's not an app but shown as an app) is always DWM.exe unless another executable is really called and used. This is already well done (again not perfect but still not bad). The argumentation that the integrated "apps" take too much CPU is mostly only IMHO if a) MS fucked up an update b) infection or c) if the process is really used e.g. trustedinstaller (while doing some background stuff/optimizations) but that usually won't take forever (unless there is a problem of course).

3. Bitsum Process Lasso is a placebo if you have a good task manager (not the crap from MS) you already can set all of this (4 free) via process explorer or process hacker. Process Lasso makes money with a feature which windows provide 4 free. It's questionable if it works in modern games because the game normally takes care of it automatically and even tries to override the manual set preference. 


Lots of those programs/tips are from XP times and not really nessary anymore.
