### ISSUE TITLE
bcdedit /set useplatformtick yes harmful on 1909?

### ISSUE THREAD

**Issue by kurtextrem** [CHEF-KOCH/GamingTweaks#49]
As I can not comment anymore on the HPET issue, I leave this here: https://www.overclock.net/forum/375-mice/1742922-win-10-1909-bcdedit-set-useplatformtick-yes-causes-input-lag-4.html. It seems like useplatformtick does harm at least on some PCs?

**Comment by CHEF-KOCH** [comment]
[Windows 2004 is out](https://gist.github.com/CHEF-KOCH/7ab8229825cf6912d1a6db3a0a4f39c1), that been said, every older OS will not be covered here. 

I simply have no time to look into older OS nor do I have interests in it, I also think I was very clear [in the old thread](https://github.com/CHEF-KOCH/GamingTweaks/issues/18) that this is scenario specific. 

But here again:
* `bcdedit /set useplatformtick yes` was never a tweak, it's a [debug flag](https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/bcdedit--set)
* HPET MUST be enabled in BIOS (newer mobos/bios do not have any HPET option anymore because it's enabled by default especially on AMD). Disabling HPET in Bios will break Windows timers. If you want you can disable under Windows specific flags regarding this, which forces Windows to user other timers (e.g. QPF, RTC as fallback). Some programs are depending on HPET on (BIOS) to obtain valid values.
* Windows 10 by default uses TSC. 
* No matter what you set, the best time you will get is 1.0 because background applications as well as the upper framework (like e.g. electron framework) will use 1.0 ms no matter if you force other values. This can be observed by generating a energy plan report and compare the values with e.g. stream running in the background and without (Steam application is basically Chromium based "browser") which then shows 1.0.
* Deleting useplatformclock is the best and any other advice lacks proof. 
* Games do not "intercepting" into HPET, what does the procedure is the upper kernel layer which is often wrongly called "kernel mode".
* Mouse tester is not a proof for something, your mouse driver can interfere, there could have been other backgrounds apps running or you simply added other tweaks on your system or you installed/updated other drivers which might intercepting with it. Besides, is mouse tester a years old utility which never got updated and is there before not an accurate measuring tool. A accurate tool is for example [Windows Performance Toolkit](https://docs.microsoft.com/en-us/windows-hardware/test/wpt/)/[analyzer](https://docs.microsoft.com/en-us/windows-hardware/test/wpt/windows-performance-analyzer) and not tools written by single individuals without releasing the source code to find out how the tool actually really works and how it "counts" or deals with margin of errors.


***Windows 2004**
Enable (if possible or not already enabled) HPET in Bios enabled, then install Windows 10 2004 ONCE fresh which is important because if you upgrade the OS Windows 10 might not set the internal timing method to "auto". If that is once done, you can (next time) when MS releases an update go ahead and in-place because this entire procedure only needs to be done once.
