### ISSUE TITLE
Electrical issue causing input de-synchronization or input loss

### ISSUE THREAD

**Issue by CiHel** [CHEF-KOCH/GamingTweaks#56]
Original Thread:
- [The most complex and elusive PC/Hardware issue I have ever encountered. Mouse/Keyboard input lag related](https://www.overclock.net/forum/375-mice/1736496-most-complex-elusive-pc-hardware-issue-i-have-ever-encountered-mouse-keyboard-input-lag-related.html)

New Thread:
- [Electrical issue causing input de-synchronization or input loss
](https://www.overclock.net/forum/375-mice/1744698-electrical-issue-causing-input-de-synchronization-input-loss.html)

Perfect mouse movement (example)
https://twitter.com/CaIypto/status/1118035985323974656

Edit:
- Changed title
- Added original thread

**Comment by CHEF-KOCH** [comment]
<details>
  <summary>Spoiler warning</summary>
  
  I have no clue how to handles this thread here nor what people expect me to answer here.
  
</details>

I try to keep it short and answer the correct findings based on the two given posts.


Does electric fluctuations influence PC hardware?

Yes.

Is this placebo?

No.

Are there some buffers used e.g. in your PSU?

Yes. This means you will still be able to use your hardware like normal but there are possible side effects (exception: total failure of course).

Are fluctuations noticeable, in-game or under the OS itself?

Yes, it depends on how sensitive you are to it, some people might never notice it, others might notice it immediately.

Is there something like "dirty electricity"? 

No, this is basically only another term for high-frequency voltage transients [HFVT](https://www.nature.com/articles/jes20108). Basically spoken it's just another term for spikes and surges of electromagnetic energy waves traveling along power lines and building wiring whee only standard 60/60Hz AC electricity should be. The observation can be made with "special" devices. The wrong terminologie was spread by several companies who sell [those devices Broadband EMI Dirty Electricity Meter](https://www.amazon.com/dp/B01MEFVYQD). Dirty simply imply that there is something in the line which does not belong into the line.

Can this influence mouse input and/or cause jitters as well as interrupts?

Yes, but most people will not notice it because if there is no direct comparison you will often blame the OS/Drivers for "strange lags". People [reported](https://www.nvidia.com/en-us/geforce/forums/discover/235326/mouse-input-lag-is-killing-me/) that the only solution is to use ["filters"](https://en.wikipedia.org/wiki/Electronic_filter) or move to another apartment with better grounding.

Is this an OS issue?

No.


### [Workarounds](https://www.vertiv.com/en-us/about/news-and-insights/articles/educational-articles/what-causes-dirty-power/)
- Change the light bulbs (yes it's no joke)
- [Buy a filter for your house](https://www.youtube.com/watch?v=cwHmXJ5mqRc) there are also [smaller filters](https://www.amazon.com/dp/B01M6XNTO9) which you can use for your PSU
- Get rid of light dimmer switches
- Change or unplug your TV
- Remove/unplug or change your cordless phone systems
- Solar power systems can also cause problems if they are not correctly isolated from your main electricity (they need a special filter) and professional people who install them correctly
- Automatic voltage regulations maintains healthy voltage conditions without using battery power can reduce or eliminate the issue

**Comment by CiHel** [comment]
thank you spent so much time
