### ISSUE TITLE
Feedback by djdallmann

### ISSUE THREAD

**Issue by djdallmann** [CHEF-KOCH/GamingTweaks#6]
Hello,

I happen to stumble upon this and like what you're doing, eerily I started something similar recently because I was tired of reading tons of recommendations without any of those people providing supporting information or tests to quantify some of the changes being made. I'm still researching quite a bit looking for conclusive evidence to provide recommendations for some.

https://github.com/djdallmann/GamingPCSetup

Under Myths you mention that Disabling C-States is not a good idea, however you mention doing so in your guide twice. Not sure if this needs more clarity like specific C-States vs all.

In regards to secure boot I believe not everyone can enable this due to ties to specific compatible hardware (certain video cards etc)

Core Parking Any Version of Windows - I recall reading that the high performance power profile eliminates the need to do this since CPU min/max is set to 100% however when set to balanced or power saving it will park some of the CPUs.

Adjusting MTU & RWIN may make small improvements to latency and packet processing by intermediary routing devices, as for hit-reg saying this may potentially be mis-leading or you could provide some reasons why. For MTU testing you could add something like PING with forced mtu and do not fragment option for determining if smaller MTU is needed but I also agree 99% not needed for most people since MTU is standard and bandwidth is plenty.

Another subject i'm also researching is the Network settings for Intel network adapters for example, trying to find evidence to support some of the claims or the need to make them. This is a good reference for them in general
https://www.intel.ca/content/www/ca/en/support/articles/000005593/network-and-i-o/ethernet-products.html
https://www.intel.ca/content/www/ca/en/support/articles/000005811/network-and-i-o/ethernet-products.html

In regards to QoS, I think bufferbloat (sounds made up.. but it's a term, haha) deserves mention as there is repeatable tests to indicate if it is present or impacting your network experience.
https://www.bufferbloat.net/projects/
https://www.ietf.org/proceedings/80/slides/tsvarea-1.pdf
https://www.youtube.com/watch?v=NuHYOu4aAqg (mentions significant impact to online games like quake etc)

Nvidia Optimizations, 
max pre-rendered frames
This has a minimum value of 1 although it said 0 in older driver versions, this reduces processing time which can result in lower latency or in some cases instability. This may be more noticeable for people with lower refresh rates 100 and below, if you have 144hz monitor your frame times are around 10ms. The statement regarding hit-reg may need more context, the users experience may be improved due to lower latency (better mouse control/input) however whether or not shots hit may not be an accurate statement.

Threaded optimization
Nvidia recommends leaving this off for some older games, it mentions this in the NV control panel. It also has the potential to lower latency but can also lower overall fps in some cases.

I really like the additional information about HPET studies, I don't recommend putting this on currently in my guide.

Your name is vaguely familiar from the Counter-Strike scene, not sure if there's any relation.

**Comment by CHEF-KOCH** [comment]
Thanks for the feedback! That's what I need here in this little project. 

I'm going to look in all of your mentioned sub-topics and see what i can do. 

About my nickname, no I'm not David Nagel but yeah I also played CS 1.6 and Go (but my times for this are over since I'm old and slow now).

**Comment by CHEF-KOCH** [comment]
> Under Myths you mention that Disabling C-States is not a good idea, however you mention doing so in your guide twice. Not sure if this needs more clarity like specific C-States vs all.

Well it's mentioned that this only applies in case you OC (which makes sense because it's about stability).

> Core Parking Any Version of Windows - I recall reading that the high performance power profile eliminates the need to do this since CPU min/max is set to 100% however when set to balanced or power saving it will park some of the CPUs.

This is [game specific and not Windows specific issue](https://answers.microsoft.com/en-us/windows/forum/games_windows_10/parked-cores-windows-10/27f33fd2-e264-4a4f-87f4-82f5fe47dfea). Whenever you use a different energy profile Windows will take care of it. You can check this even with the normal resource monitor utility. I highly suggest to not touch anything unless you really have a performance problem, the better fix would be to contact the developer and ask him to fix this I also don't like to run tasks/programs in order to tweak something. This problem is also soon or later obsolete since every game which was developed after 2008 utilities more than 2 cores (unless explicitly opt-out) because every game engine adopted that feature to check the CPU. 

> Adjusting MTU & RWIN may make small improvements to latency and packet processing by intermediary routing devices, as for hit-reg saying this may potentially be mis-leading or you could provide some reasons why. For MTU testing you could add something like PING with forced mtu and do not fragment option for determining if smaller MTU is needed but I also agree 99% not needed for most people since MTU is standard and bandwidth is plenty.

I tested this in various games and never saw any difference, I guess it's placebo anyway because Windows auto-tunes the value based on the driver settings (if avbl.) I know some drivers don't offer such manual tweaking (Intel e.g. does) in this case I would agree, however there are some games which are special in how they handle it but I would say that this tweak will be obsolete too since the most impact is how you router firmware was configured, if it uses lower values than Windows then the Windows settings doesn't matter at all and you see no effect.

> Another subject i'm also researching is the Network settings for Intel network adapters for example, trying to find evidence to support some of the claims or the need to make them. This is a good reference for them in general

There is in one of my gists my own settings on it, however, this is also game specific, the problem here is that it can cause more harm because the wrong settings might result in the opposite. 

> In regards to QoS, I think bufferbloat (sounds made up.. but it's a term, haha) deserves mention as there is repeatable tests to indicate if it is present or impacting your network experience.

I'm not sure why this must be mentioned, this is a gaming tweaks repo based upon Windows (sub-optimal) settings and it seems that this is depending on which firmware is running on your router. Assuming you're a gamer you usually don't use a router which is older than 10 years (because that is a problem from this time). If you're a streamer and in case you are really affected (like [this guy](https://obsproject.com/forum/resources/bufferbloat-and-streaming.729/)) you might can use additional alorithm within e.g, OBS (they call it low-latency mode) in order to address this. However, I'm not sure what I should write/add here and I don't believe any modern Router has this problem (assuming they implemented the latest standards).

> Nvidia Optimizations

Point taken it's simply outdated. The default values are fine (because I complaint years until NV finally changed it) and the game specific "tweaks" can be done under the tab where you can see/add your own apps/games. I might only link the [TweakGuides article](http://www.tweakguides.com/NVFORCE_6.html) here because it explains each and one of the nVidia toggles in detail.

However I have a folder on Twitch etc. which I update often which is game specific which I could add in this repo, so everyone could go ahead grab it.

**Comment by CHEF-KOCH** [comment]
I close here, try to address the suggested things and if there is some real evidence to use xyz I like to know. 

Thanks again for the review/feedback.
