### ISSUE TITLE
Mentioning ISLC in OS (general) as well

### ISSUE THREAD

**Issue by 0815Hunter** [CHEF-KOCH/GamingTweaks#81]
ISLC is the most handy tool (2in1, autostart) , but only mentioned in the [Drivers Guide](https://github.com/CHEF-KOCH/GamingTweaks/tree/master/Drivers#nvidia-driver-update-procedure) at the moment.

Shouldn't it be put into the OS (general) Guide ([Timer Resolution](https://github.com/CHEF-KOCH/GamingTweaks/blob/master/OS%20(general)/Readme.md#os-timer-resolution) &  [fix-memory-issue](https://github.com/CHEF-KOCH/GamingTweaks/blob/master/OS%20(general)/Readme.md#fix-memory-issue-before-with-windows-10-build-1607-anniversary-update)) as well?

Thanks for putting so much work into this Guide!

**Comment by CHEF-KOCH** [comment]
It will be removed because it's not needed anymore since 1809/1093 (or higher). Since gamers should use the latest programs I see no reason to mention it anymore.

The author himself also wrote this on Guru3d that this OS issue got fixed. Core prio and Memory related bugs are no problem anymore in today's 2004 build.

I in general dislike the idea that gamer should use/install xyz program, my preference is that if you find problems, that you report it over to MS so that this gets fixed, so this means the tool always was only a workaround.
